/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ChallengesRouteImport } from './routes/challenges'
import { Route as DailyRouteImport } from './routes/daily'
import { Route as EliminationRouteImport } from './routes/elimination'
import { Route as FriendsRouteImport } from './routes/friends'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as LessonResultRouteImport } from './routes/lesson-result'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as RoomRouteImport } from './routes/room'
import { Route as SchoolsRouteImport } from './routes/schools'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as TravelRouteImport } from './routes/travel'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAchievementsRouteImport } from './routes/admin.achievements'
import { Route as AdminAdsRouteImport } from './routes/admin.ads'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminAudiosRouteImport } from './routes/admin.audios'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminCoursesRouteImport } from './routes/admin.courses'
import { Route as AdminDailyRouteImport } from './routes/admin.daily'
import { Route as AdminExercisesRouteImport } from './routes/admin.exercises'
import { Route as AdminLanguagesRouteImport } from './routes/admin.languages'
import { Route as AdminMultiplayerRouteImport } from './routes/admin.multiplayer'
import { Route as AdminPhrasesRouteImport } from './routes/admin.phrases'
import { Route as AdminPremiumRouteImport } from './routes/admin.premium'
import { Route as AdminRankingsRouteImport } from './routes/admin.rankings'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminReviewRouteImport } from './routes/admin.review'
import { Route as AdminSearchRouteImport } from './routes/admin.search'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminVocabularyRouteImport } from './routes/admin.vocabulary'
import { Route as AdminForbiddenRouteImport } from './routes/admin_.forbidden'
import { Route as AdminLoginRouteImport } from './routes/admin_.login'
import { Route as AdminSessionExpiredRouteImport } from './routes/admin_.session-expired'
import { Route as AdminUnauthorizedRouteImport } from './routes/admin_.unauthorized'
import { Route as LessonLessonIdRouteImport } from './routes/lesson.$lessonId'
import { Route as PlayDuelRouteImport } from './routes/play.duel'
import { Route as PlayJoinRouteImport } from './routes/play.join'
import { Route as PlayPrivateRouteImport } from './routes/play.private'
import { Route as PlayResultsRouteImport } from './routes/play.results'
import { Route as PlaySurvivalRouteImport } from './routes/play.survival'
import { Route as PlayTeamsRouteImport } from './routes/play.teams'
import { Route as PlayTournamentsRouteImport } from './routes/play.tournaments'
import { Route as UserUserIdRouteImport } from './routes/user.$userId'
import { Route as AdminLessonsIndexRouteImport } from './routes/admin.lessons.index'
import { Route as AdminLessonsLessonIdRouteImport } from './routes/admin.lessons.$lessonId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesRoute = ChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyRoute = DailyRouteImport.update({
  id: '/daily',
  path: '/daily',
  getParentRoute: () => rootRouteImport,
} as any)
const EliminationRoute = EliminationRouteImport.update({
  id: '/elimination',
  path: '/elimination',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsRoute = FriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonResultRoute = LessonResultRouteImport.update({
  id: '/lesson-result',
  path: '/lesson-result',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomRoute = RoomRouteImport.update({
  id: '/room',
  path: '/room',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolsRoute = SchoolsRouteImport.update({
  id: '/schools',
  path: '/schools',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const TravelRoute = TravelRouteImport.update({
  id: '/travel',
  path: '/travel',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAchievementsRoute = AdminAchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdsRoute = AdminAdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAudiosRoute = AdminAudiosRouteImport.update({
  id: '/audios',
  path: '/audios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoursesRoute = AdminCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDailyRoute = AdminDailyRouteImport.update({
  id: '/daily',
  path: '/daily',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExercisesRoute = AdminExercisesRouteImport.update({
  id: '/exercises',
  path: '/exercises',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLanguagesRoute = AdminLanguagesRouteImport.update({
  id: '/languages',
  path: '/languages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMultiplayerRoute = AdminMultiplayerRouteImport.update({
  id: '/multiplayer',
  path: '/multiplayer',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPhrasesRoute = AdminPhrasesRouteImport.update({
  id: '/phrases',
  path: '/phrases',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPremiumRoute = AdminPremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRankingsRoute = AdminRankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewRoute = AdminReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSearchRoute = AdminSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVocabularyRoute = AdminVocabularyRouteImport.update({
  id: '/vocabulary',
  path: '/vocabulary',
  getParentRoute: () => AdminRoute,
} as any)
const AdminForbiddenRoute = AdminForbiddenRouteImport.update({
  id: '/admin_/forbidden',
  path: '/admin/forbidden',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin_/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSessionExpiredRoute = AdminSessionExpiredRouteImport.update({
  id: '/admin_/session-expired',
  path: '/admin/session-expired',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUnauthorizedRoute = AdminUnauthorizedRouteImport.update({
  id: '/admin_/unauthorized',
  path: '/admin/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonLessonIdRoute = LessonLessonIdRouteImport.update({
  id: '/lesson/$lessonId',
  path: '/lesson/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayDuelRoute = PlayDuelRouteImport.update({
  id: '/play/duel',
  path: '/play/duel',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayJoinRoute = PlayJoinRouteImport.update({
  id: '/play/join',
  path: '/play/join',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayPrivateRoute = PlayPrivateRouteImport.update({
  id: '/play/private',
  path: '/play/private',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayResultsRoute = PlayResultsRouteImport.update({
  id: '/play/results',
  path: '/play/results',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaySurvivalRoute = PlaySurvivalRouteImport.update({
  id: '/play/survival',
  path: '/play/survival',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayTeamsRoute = PlayTeamsRouteImport.update({
  id: '/play/teams',
  path: '/play/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayTournamentsRoute = PlayTournamentsRouteImport.update({
  id: '/play/tournaments',
  path: '/play/tournaments',
  getParentRoute: () => rootRouteImport,
} as any)
const UserUserIdRoute = UserUserIdRouteImport.update({
  id: '/user/$userId',
  path: '/user/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLessonsIndexRoute = AdminLessonsIndexRouteImport.update({
  id: '/lessons/',
  path: '/lessons/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLessonsLessonIdRoute = AdminLessonsLessonIdRouteImport.update({
  id: '/lessons/$lessonId',
  path: '/lessons/$lessonId',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/admin': typeof AdminRouteWithChildren
  '/challenges': typeof ChallengesRoute
  '/daily': typeof DailyRoute
  '/elimination': typeof EliminationRoute
  '/friends': typeof FriendsRoute
  '/learn': typeof LearnRoute
  '/lesson-result': typeof LessonResultRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/premium': typeof PremiumRoute
  '/profile': typeof ProfileRoute
  '/quiz': typeof QuizRoute
  '/ranking': typeof RankingRoute
  '/room': typeof RoomRoute
  '/schools': typeof SchoolsRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRoute
  '/travel': typeof TravelRoute
  '/admin/achievements': typeof AdminAchievementsRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audios': typeof AdminAudiosRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/daily': typeof AdminDailyRoute
  '/admin/exercises': typeof AdminExercisesRoute
  '/admin/languages': typeof AdminLanguagesRoute
  '/admin/multiplayer': typeof AdminMultiplayerRoute
  '/admin/phrases': typeof AdminPhrasesRoute
  '/admin/premium': typeof AdminPremiumRoute
  '/admin/rankings': typeof AdminRankingsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/review': typeof AdminReviewRoute
  '/admin/search': typeof AdminSearchRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vocabulary': typeof AdminVocabularyRoute
  '/admin/forbidden': typeof AdminForbiddenRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/session-expired': typeof AdminSessionExpiredRoute
  '/admin/unauthorized': typeof AdminUnauthorizedRoute
  '/lesson/$lessonId': typeof LessonLessonIdRoute
  '/play/duel': typeof PlayDuelRoute
  '/play/join': typeof PlayJoinRoute
  '/play/private': typeof PlayPrivateRoute
  '/play/results': typeof PlayResultsRoute
  '/play/survival': typeof PlaySurvivalRoute
  '/play/teams': typeof PlayTeamsRoute
  '/play/tournaments': typeof PlayTournamentsRoute
  '/user/$userId': typeof UserUserIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/lessons/$lessonId': typeof AdminLessonsLessonIdRoute
  '/admin/lessons/': typeof AdminLessonsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/challenges': typeof ChallengesRoute
  '/daily': typeof DailyRoute
  '/elimination': typeof EliminationRoute
  '/friends': typeof FriendsRoute
  '/learn': typeof LearnRoute
  '/lesson-result': typeof LessonResultRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/premium': typeof PremiumRoute
  '/profile': typeof ProfileRoute
  '/quiz': typeof QuizRoute
  '/ranking': typeof RankingRoute
  '/room': typeof RoomRoute
  '/schools': typeof SchoolsRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRoute
  '/travel': typeof TravelRoute
  '/admin/achievements': typeof AdminAchievementsRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audios': typeof AdminAudiosRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/daily': typeof AdminDailyRoute
  '/admin/exercises': typeof AdminExercisesRoute
  '/admin/languages': typeof AdminLanguagesRoute
  '/admin/multiplayer': typeof AdminMultiplayerRoute
  '/admin/phrases': typeof AdminPhrasesRoute
  '/admin/premium': typeof AdminPremiumRoute
  '/admin/rankings': typeof AdminRankingsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/review': typeof AdminReviewRoute
  '/admin/search': typeof AdminSearchRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vocabulary': typeof AdminVocabularyRoute
  '/admin/forbidden': typeof AdminForbiddenRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/session-expired': typeof AdminSessionExpiredRoute
  '/admin/unauthorized': typeof AdminUnauthorizedRoute
  '/lesson/$lessonId': typeof LessonLessonIdRoute
  '/play/duel': typeof PlayDuelRoute
  '/play/join': typeof PlayJoinRoute
  '/play/private': typeof PlayPrivateRoute
  '/play/results': typeof PlayResultsRoute
  '/play/survival': typeof PlaySurvivalRoute
  '/play/teams': typeof PlayTeamsRoute
  '/play/tournaments': typeof PlayTournamentsRoute
  '/user/$userId': typeof UserUserIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/lessons/$lessonId': typeof AdminLessonsLessonIdRoute
  '/admin/lessons': typeof AdminLessonsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/admin': typeof AdminRouteWithChildren
  '/challenges': typeof ChallengesRoute
  '/daily': typeof DailyRoute
  '/elimination': typeof EliminationRoute
  '/friends': typeof FriendsRoute
  '/learn': typeof LearnRoute
  '/lesson-result': typeof LessonResultRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/premium': typeof PremiumRoute
  '/profile': typeof ProfileRoute
  '/quiz': typeof QuizRoute
  '/ranking': typeof RankingRoute
  '/room': typeof RoomRoute
  '/schools': typeof SchoolsRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRoute
  '/travel': typeof TravelRoute
  '/admin/achievements': typeof AdminAchievementsRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audios': typeof AdminAudiosRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/daily': typeof AdminDailyRoute
  '/admin/exercises': typeof AdminExercisesRoute
  '/admin/languages': typeof AdminLanguagesRoute
  '/admin/multiplayer': typeof AdminMultiplayerRoute
  '/admin/phrases': typeof AdminPhrasesRoute
  '/admin/premium': typeof AdminPremiumRoute
  '/admin/rankings': typeof AdminRankingsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/review': typeof AdminReviewRoute
  '/admin/search': typeof AdminSearchRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vocabulary': typeof AdminVocabularyRoute
  '/admin_/forbidden': typeof AdminForbiddenRoute
  '/admin_/login': typeof AdminLoginRoute
  '/admin_/session-expired': typeof AdminSessionExpiredRoute
  '/admin_/unauthorized': typeof AdminUnauthorizedRoute
  '/lesson/$lessonId': typeof LessonLessonIdRoute
  '/play/duel': typeof PlayDuelRoute
  '/play/join': typeof PlayJoinRoute
  '/play/private': typeof PlayPrivateRoute
  '/play/results': typeof PlayResultsRoute
  '/play/survival': typeof PlaySurvivalRoute
  '/play/teams': typeof PlayTeamsRoute
  '/play/tournaments': typeof PlayTournamentsRoute
  '/user/$userId': typeof UserUserIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/lessons/$lessonId': typeof AdminLessonsLessonIdRoute
  '/admin/lessons/': typeof AdminLessonsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/achievements'
    | '/admin'
    | '/challenges'
    | '/daily'
    | '/elimination'
    | '/friends'
    | '/learn'
    | '/lesson-result'
    | '/login'
    | '/notifications'
    | '/onboarding'
    | '/premium'
    | '/profile'
    | '/quiz'
    | '/ranking'
    | '/room'
    | '/schools'
    | '/settings'
    | '/shop'
    | '/travel'
    | '/admin/achievements'
    | '/admin/ads'
    | '/admin/analytics'
    | '/admin/audios'
    | '/admin/audit'
    | '/admin/courses'
    | '/admin/daily'
    | '/admin/exercises'
    | '/admin/languages'
    | '/admin/multiplayer'
    | '/admin/phrases'
    | '/admin/premium'
    | '/admin/rankings'
    | '/admin/reports'
    | '/admin/review'
    | '/admin/search'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/vocabulary'
    | '/admin/forbidden'
    | '/admin/login'
    | '/admin/session-expired'
    | '/admin/unauthorized'
    | '/lesson/$lessonId'
    | '/play/duel'
    | '/play/join'
    | '/play/private'
    | '/play/results'
    | '/play/survival'
    | '/play/teams'
    | '/play/tournaments'
    | '/user/$userId'
    | '/admin/'
    | '/admin/lessons/$lessonId'
    | '/admin/lessons/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/achievements'
    | '/challenges'
    | '/daily'
    | '/elimination'
    | '/friends'
    | '/learn'
    | '/lesson-result'
    | '/login'
    | '/notifications'
    | '/onboarding'
    | '/premium'
    | '/profile'
    | '/quiz'
    | '/ranking'
    | '/room'
    | '/schools'
    | '/settings'
    | '/shop'
    | '/travel'
    | '/admin/achievements'
    | '/admin/ads'
    | '/admin/analytics'
    | '/admin/audios'
    | '/admin/audit'
    | '/admin/courses'
    | '/admin/daily'
    | '/admin/exercises'
    | '/admin/languages'
    | '/admin/multiplayer'
    | '/admin/phrases'
    | '/admin/premium'
    | '/admin/rankings'
    | '/admin/reports'
    | '/admin/review'
    | '/admin/search'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/vocabulary'
    | '/admin/forbidden'
    | '/admin/login'
    | '/admin/session-expired'
    | '/admin/unauthorized'
    | '/lesson/$lessonId'
    | '/play/duel'
    | '/play/join'
    | '/play/private'
    | '/play/results'
    | '/play/survival'
    | '/play/teams'
    | '/play/tournaments'
    | '/user/$userId'
    | '/admin'
    | '/admin/lessons/$lessonId'
    | '/admin/lessons'
  id:
    | '__root__'
    | '/'
    | '/achievements'
    | '/admin'
    | '/challenges'
    | '/daily'
    | '/elimination'
    | '/friends'
    | '/learn'
    | '/lesson-result'
    | '/login'
    | '/notifications'
    | '/onboarding'
    | '/premium'
    | '/profile'
    | '/quiz'
    | '/ranking'
    | '/room'
    | '/schools'
    | '/settings'
    | '/shop'
    | '/travel'
    | '/admin/achievements'
    | '/admin/ads'
    | '/admin/analytics'
    | '/admin/audios'
    | '/admin/audit'
    | '/admin/courses'
    | '/admin/daily'
    | '/admin/exercises'
    | '/admin/languages'
    | '/admin/multiplayer'
    | '/admin/phrases'
    | '/admin/premium'
    | '/admin/rankings'
    | '/admin/reports'
    | '/admin/review'
    | '/admin/search'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/vocabulary'
    | '/admin_/forbidden'
    | '/admin_/login'
    | '/admin_/session-expired'
    | '/admin_/unauthorized'
    | '/lesson/$lessonId'
    | '/play/duel'
    | '/play/join'
    | '/play/private'
    | '/play/results'
    | '/play/survival'
    | '/play/teams'
    | '/play/tournaments'
    | '/user/$userId'
    | '/admin/'
    | '/admin/lessons/$lessonId'
    | '/admin/lessons/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AchievementsRoute: typeof AchievementsRoute
  AdminRoute: typeof AdminRouteWithChildren
  ChallengesRoute: typeof ChallengesRoute
  DailyRoute: typeof DailyRoute
  EliminationRoute: typeof EliminationRoute
  FriendsRoute: typeof FriendsRoute
  LearnRoute: typeof LearnRoute
  LessonResultRoute: typeof LessonResultRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  OnboardingRoute: typeof OnboardingRoute
  PremiumRoute: typeof PremiumRoute
  ProfileRoute: typeof ProfileRoute
  QuizRoute: typeof QuizRoute
  RankingRoute: typeof RankingRoute
  RoomRoute: typeof RoomRoute
  SchoolsRoute: typeof SchoolsRoute
  SettingsRoute: typeof SettingsRoute
  ShopRoute: typeof ShopRoute
  TravelRoute: typeof TravelRoute
  AdminForbiddenRoute: typeof AdminForbiddenRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminSessionExpiredRoute: typeof AdminSessionExpiredRoute
  AdminUnauthorizedRoute: typeof AdminUnauthorizedRoute
  LessonLessonIdRoute: typeof LessonLessonIdRoute
  PlayDuelRoute: typeof PlayDuelRoute
  PlayJoinRoute: typeof PlayJoinRoute
  PlayPrivateRoute: typeof PlayPrivateRoute
  PlayResultsRoute: typeof PlayResultsRoute
  PlaySurvivalRoute: typeof PlaySurvivalRoute
  PlayTeamsRoute: typeof PlayTeamsRoute
  PlayTournamentsRoute: typeof PlayTournamentsRoute
  UserUserIdRoute: typeof UserUserIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges': {
      id: '/challenges'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof ChallengesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily': {
      id: '/daily'
      path: '/daily'
      fullPath: '/daily'
      preLoaderRoute: typeof DailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elimination': {
      id: '/elimination'
      path: '/elimination'
      fullPath: '/elimination'
      preLoaderRoute: typeof EliminationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends': {
      id: '/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof FriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson-result': {
      id: '/lesson-result'
      path: '/lesson-result'
      fullPath: '/lesson-result'
      preLoaderRoute: typeof LessonResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room': {
      id: '/room'
      path: '/room'
      fullPath: '/room'
      preLoaderRoute: typeof RoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schools': {
      id: '/schools'
      path: '/schools'
      fullPath: '/schools'
      preLoaderRoute: typeof SchoolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/travel': {
      id: '/travel'
      path: '/travel'
      fullPath: '/travel'
      preLoaderRoute: typeof TravelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/achievements': {
      id: '/admin/achievements'
      path: '/achievements'
      fullPath: '/admin/achievements'
      preLoaderRoute: typeof AdminAchievementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ads': {
      id: '/admin/ads'
      path: '/ads'
      fullPath: '/admin/ads'
      preLoaderRoute: typeof AdminAdsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audios': {
      id: '/admin/audios'
      path: '/audios'
      fullPath: '/admin/audios'
      preLoaderRoute: typeof AdminAudiosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/courses': {
      id: '/admin/courses'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AdminCoursesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/daily': {
      id: '/admin/daily'
      path: '/daily'
      fullPath: '/admin/daily'
      preLoaderRoute: typeof AdminDailyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/exercises': {
      id: '/admin/exercises'
      path: '/exercises'
      fullPath: '/admin/exercises'
      preLoaderRoute: typeof AdminExercisesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/languages': {
      id: '/admin/languages'
      path: '/languages'
      fullPath: '/admin/languages'
      preLoaderRoute: typeof AdminLanguagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/multiplayer': {
      id: '/admin/multiplayer'
      path: '/multiplayer'
      fullPath: '/admin/multiplayer'
      preLoaderRoute: typeof AdminMultiplayerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/phrases': {
      id: '/admin/phrases'
      path: '/phrases'
      fullPath: '/admin/phrases'
      preLoaderRoute: typeof AdminPhrasesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/premium': {
      id: '/admin/premium'
      path: '/premium'
      fullPath: '/admin/premium'
      preLoaderRoute: typeof AdminPremiumRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rankings': {
      id: '/admin/rankings'
      path: '/rankings'
      fullPath: '/admin/rankings'
      preLoaderRoute: typeof AdminRankingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/review': {
      id: '/admin/review'
      path: '/review'
      fullPath: '/admin/review'
      preLoaderRoute: typeof AdminReviewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/search': {
      id: '/admin/search'
      path: '/search'
      fullPath: '/admin/search'
      preLoaderRoute: typeof AdminSearchRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/vocabulary': {
      id: '/admin/vocabulary'
      path: '/vocabulary'
      fullPath: '/admin/vocabulary'
      preLoaderRoute: typeof AdminVocabularyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin_/forbidden': {
      id: '/admin_/forbidden'
      path: '/admin/forbidden'
      fullPath: '/admin/forbidden'
      preLoaderRoute: typeof AdminForbiddenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/login': {
      id: '/admin_/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/session-expired': {
      id: '/admin_/session-expired'
      path: '/admin/session-expired'
      fullPath: '/admin/session-expired'
      preLoaderRoute: typeof AdminSessionExpiredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/unauthorized': {
      id: '/admin_/unauthorized'
      path: '/admin/unauthorized'
      fullPath: '/admin/unauthorized'
      preLoaderRoute: typeof AdminUnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson/$lessonId': {
      id: '/lesson/$lessonId'
      path: '/lesson/$lessonId'
      fullPath: '/lesson/$lessonId'
      preLoaderRoute: typeof LessonLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/duel': {
      id: '/play/duel'
      path: '/play/duel'
      fullPath: '/play/duel'
      preLoaderRoute: typeof PlayDuelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/join': {
      id: '/play/join'
      path: '/play/join'
      fullPath: '/play/join'
      preLoaderRoute: typeof PlayJoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/private': {
      id: '/play/private'
      path: '/play/private'
      fullPath: '/play/private'
      preLoaderRoute: typeof PlayPrivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/results': {
      id: '/play/results'
      path: '/play/results'
      fullPath: '/play/results'
      preLoaderRoute: typeof PlayResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/survival': {
      id: '/play/survival'
      path: '/play/survival'
      fullPath: '/play/survival'
      preLoaderRoute: typeof PlaySurvivalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/teams': {
      id: '/play/teams'
      path: '/play/teams'
      fullPath: '/play/teams'
      preLoaderRoute: typeof PlayTeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/tournaments': {
      id: '/play/tournaments'
      path: '/play/tournaments'
      fullPath: '/play/tournaments'
      preLoaderRoute: typeof PlayTournamentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$userId': {
      id: '/user/$userId'
      path: '/user/$userId'
      fullPath: '/user/$userId'
      preLoaderRoute: typeof UserUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/lessons/': {
      id: '/admin/lessons/'
      path: '/lessons'
      fullPath: '/admin/lessons/'
      preLoaderRoute: typeof AdminLessonsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lessons/$lessonId': {
      id: '/admin/lessons/$lessonId'
      path: '/lessons/$lessonId'
      fullPath: '/admin/lessons/$lessonId'
      preLoaderRoute: typeof AdminLessonsLessonIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAchievementsRoute: typeof AdminAchievementsRoute
  AdminAdsRoute: typeof AdminAdsRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAudiosRoute: typeof AdminAudiosRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminCoursesRoute: typeof AdminCoursesRoute
  AdminDailyRoute: typeof AdminDailyRoute
  AdminExercisesRoute: typeof AdminExercisesRoute
  AdminLanguagesRoute: typeof AdminLanguagesRoute
  AdminMultiplayerRoute: typeof AdminMultiplayerRoute
  AdminPhrasesRoute: typeof AdminPhrasesRoute
  AdminPremiumRoute: typeof AdminPremiumRoute
  AdminRankingsRoute: typeof AdminRankingsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminReviewRoute: typeof AdminReviewRoute
  AdminSearchRoute: typeof AdminSearchRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVocabularyRoute: typeof AdminVocabularyRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminLessonsLessonIdRoute: typeof AdminLessonsLessonIdRoute
  AdminLessonsIndexRoute: typeof AdminLessonsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAchievementsRoute: AdminAchievementsRoute,
  AdminAdsRoute: AdminAdsRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAudiosRoute: AdminAudiosRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminCoursesRoute: AdminCoursesRoute,
  AdminDailyRoute: AdminDailyRoute,
  AdminExercisesRoute: AdminExercisesRoute,
  AdminLanguagesRoute: AdminLanguagesRoute,
  AdminMultiplayerRoute: AdminMultiplayerRoute,
  AdminPhrasesRoute: AdminPhrasesRoute,
  AdminPremiumRoute: AdminPremiumRoute,
  AdminRankingsRoute: AdminRankingsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminReviewRoute: AdminReviewRoute,
  AdminSearchRoute: AdminSearchRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVocabularyRoute: AdminVocabularyRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminLessonsLessonIdRoute: AdminLessonsLessonIdRoute,
  AdminLessonsIndexRoute: AdminLessonsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AchievementsRoute: AchievementsRoute,
  AdminRoute: AdminRouteWithChildren,
  ChallengesRoute: ChallengesRoute,
  DailyRoute: DailyRoute,
  EliminationRoute: EliminationRoute,
  FriendsRoute: FriendsRoute,
  LearnRoute: LearnRoute,
  LessonResultRoute: LessonResultRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  OnboardingRoute: OnboardingRoute,
  PremiumRoute: PremiumRoute,
  ProfileRoute: ProfileRoute,
  QuizRoute: QuizRoute,
  RankingRoute: RankingRoute,
  RoomRoute: RoomRoute,
  SchoolsRoute: SchoolsRoute,
  SettingsRoute: SettingsRoute,
  ShopRoute: ShopRoute,
  TravelRoute: TravelRoute,
  AdminForbiddenRoute: AdminForbiddenRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminSessionExpiredRoute: AdminSessionExpiredRoute,
  AdminUnauthorizedRoute: AdminUnauthorizedRoute,
  LessonLessonIdRoute: LessonLessonIdRoute,
  PlayDuelRoute: PlayDuelRoute,
  PlayJoinRoute: PlayJoinRoute,
  PlayPrivateRoute: PlayPrivateRoute,
  PlayResultsRoute: PlayResultsRoute,
  PlaySurvivalRoute: PlaySurvivalRoute,
  PlayTeamsRoute: PlayTeamsRoute,
  PlayTournamentsRoute: PlayTournamentsRoute,
  UserUserIdRoute: UserUserIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
